{
    "name": "neo-config", 
    "profiles": [
        "prod"
    ], 
    "label": null, 
    "version": null, 
    "state": null, 
    "propertySources": [
        {
            "name": "https://github.com/ityouknow/spring-cloud-starter/config-repo/neo-config-prod.properties", 
            "source": {
                "neo.hello": "hello im prod"
            }
        }
    ]
}