{
    "name": "neo-config", 
    "profiles": [
        "test"
    ], 
    "label": null, 
    "version": null, 
    "state": null, 
    "propertySources": [
        {
            "name": "https://github.com/ityouknow/spring-cloud-starter/config-repo/neo-config-test.properties", 
            "source": {
                "neo.hello": "hello im test"
            }
        }
    ]
}